package io.bandi.gamelens.batch.service;

import io.bandi.gamelens.batch.domain.model.Recommendation;
import io.bandi.gamelens.batch.repository.RecommendationRepository;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Service for querying persisted recommendations.
 *
 * <p>Recommendations are generated by the batch job, not by this service.
 * This class only exposes read access to the results.
 */
@Service
public class RecommendationService {

    private final RecommendationRepository repository;

    public RecommendationService(RecommendationRepository repository) {
        this.repository = repository;
    }

    /**
     * Returns all recommendations ordered by score descending.
     *
     * @return list of recommendations, empty if the batch job has not run yet
     */
    public List<Recommendation> getAllRecommendations() {
        return repository.findAllByOrderByScoreDesc();
    }
}
